# Generated by Django 5.2.4 on 2026-01-08 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPilot', '0002_applyjob_email_alter_applyjob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='JobPilot.createjob'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='CV/'),
        ),
    ]
