# Generated by Django 5.2.4 on 2026-01-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPilot', '0002_alter_applyjob_job_alter_applyjob_preferred_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='JobPilot.createjob'),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='experience',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=200),
        ),
    ]
